import '../../features/shop/category/data/models/category_model.dart';
import '../../utils/constants/image_strings.dart';

class CategoryDummy {
  static final List<CategoryModel> catTest = [
    CategoryModel(
      id: 1,
      name: 'Sustainable & Eco-Friendly Products',
      image: '',
      isFeatured: true,
    ),
    CategoryModel(
      id: 2,
      name: 'Hobbies & Crafts',
      image: PImages.p4,
      isFeatured: true,
      parentId: '2',
    ),
  ];
  // Main Categories (Prioritized by Sustainability, Crafts, Fashion, Food, DIY, etc.)
  static final List<CategoryModel> categories = [
    CategoryModel(
      id: 1,
      name: 'Sustainable & Eco-Friendly Products',
      image: PImages.p12,
      isFeatured: true,
    ),

    CategoryModel(
      id: 2,
      name: 'Hobbies & Crafts',
      image: PImages.p4,
      isFeatured: true,
    ),

    CategoryModel(
      id: 3,
      name: 'Fashion & Apparel',
      image: PImages.p14,
      isFeatured: true,
    ),

    CategoryModel(
      id: 4,
      name: 'Beauty & Personal Care',
      image: PImages.p5,
      isFeatured: true,
    ),

    CategoryModel(
      id: 5,
      name: 'Groceries & Food',
      image: PImages.p5,
      isFeatured: true,
    ),

    CategoryModel(
      id: 6,
      name: 'Specialty Diet & Organic Food',
      image: PImages.p2,
      isFeatured: true,
    ),

    CategoryModel(
      id: 7,
      name: 'DIY & Home Improvement',
      image: PImages.p9,
      isFeatured: true,
    ),

    CategoryModel(
      id: 8,
      name: 'Home & Furniture',
      image: PImages.p15,
      isFeatured: true,
    ),

    CategoryModel(
      id: 9,
      name: 'Home Improvement & Tools',
      image: PImages.p10,
      isFeatured: true,
    ),

    CategoryModel(
      id: 10,
      name: 'Office & School Supplies',
      image: PImages.p8,
      isFeatured: true,
    ),

    CategoryModel(
      id: 11,
      name: 'Health & Wellness',
      image: PImages.p1,
      isFeatured: true,
    ),

    CategoryModel(
      id: 12,
      name: 'Jewelry & Accessories',
      image: PImages.p13,
      isFeatured: true,
    ),

    CategoryModel(
      id: 13,
      name: 'Travel & Luggage',
      image: PImages.p3,
      isFeatured: true,
    ),

    CategoryModel(
      id: 14,
      name: 'Party & Events Supplies',
      image: PImages.p6,
      isFeatured: true,
    ),

    CategoryModel(
      id: 15,
      name: 'Pet Supplies',
      image: PImages.p11,
      isFeatured: true,
    ),

    CategoryModel(
      id: 16,
      name: 'Baby & Kids Products',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 17,
      name: 'Electronics & Gadgets',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(id: 18, name: 'Home Appliances', image: '', isFeatured: true),

    CategoryModel(
      id: 19,
      name: 'Office Electronics',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 20,
      name: 'Photography & Videography Equipment',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 21,
      name: 'Handmade & Custom Products',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 22,
      name: 'Industrial & Business Supplies',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 23,
      name: 'Automotive & Motorcycles',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 24,
      name: 'Agricultural & Farming Supplies',
      image: '',
      isFeatured: true,
    ),

    CategoryModel(
      id: 25,
      name: 'Alcohol & Beverages',
      image: '',
      isFeatured: true,
    ),

    // Subcategories for Electronics & Gadgets
    CategoryModel(
      id: 101,
      name: 'Smartphones & Accessories',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 102,
      name: 'Laptops & Computers',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 103,
      name: 'Tablets & Accessories',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 104,
      name: 'Smartwatches & Wearables',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 105,
      name: 'Headphones & Audio Devices',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 106,
      name: 'Camera & Photography Equipment',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 107,
      name: 'Gaming Consoles & Accessories',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    CategoryModel(
      id: 108,
      name: 'Home Automation & Smart Devices',
      image: '',
      isFeatured: false,
      parentId: '1',
    ),
    // Subcategories for Home Appliances
    CategoryModel(
      id: 201,
      name: 'Kitchen Appliances',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 202,
      name: 'Refrigerators & Freezers',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 203,
      name: 'Washing Machines & Dryers',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 204,
      name: 'Vacuum Cleaners & Floor Care',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 205,
      name: 'Air Conditioners & Coolers',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 206,
      name: 'Heaters & Fans',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 207,
      name: 'Ironing & Garment Care',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),
    CategoryModel(
      id: 208,
      name: 'Water Purifiers & Dispensers',
      image: '',
      isFeatured: false,
      parentId: '2',
    ),

    // Subcategories for Fashion & Apparel
    CategoryModel(
      id: 301,
      name: 'Men\'s Clothing',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 302,
      name: 'Women\'s Clothing',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 303,
      name: 'Kids\' Clothing',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 304,
      name: 'Footwear',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 305,
      name: 'Bags & Wallets',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 306,
      name: 'Hats & Caps',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 307,
      name: 'Eyewear & Sunglasses',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),
    CategoryModel(
      id: 308,
      name: 'Traditional & Cultural Wear',
      image: '',
      isFeatured: false,
      parentId: '3',
    ),

    // Subcategories for Beauty & Personal Care
    CategoryModel(
      id: 401,
      name: 'Skincare',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 402,
      name: 'Haircare',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 403,
      name: 'Makeup',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 404,
      name: 'Fragrances',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 405,
      name: 'Bath & Body',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 406,
      name: 'Men\'s Grooming',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 407,
      name: 'Oral Care',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),
    CategoryModel(
      id: 408,
      name: 'Beauty Tools & Accessories',
      image: '',
      isFeatured: false,
      parentId: '4',
    ),

    // Subcategories for Health & Wellness
    CategoryModel(
      id: 501,
      name: 'Vitamins & Supplements',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 502,
      name: 'Medical Supplies',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 503,
      name: 'Fitness & Nutrition',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 504,
      name: 'Mental Wellness',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 505,
      name: 'Personal Safety',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 506,
      name: 'Alternative & Herbal Medicine',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 507,
      name: 'Sexual Wellness',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),
    CategoryModel(
      id: 508,
      name: 'Mobility & Disability Aids',
      image: '',
      isFeatured: false,
      parentId: '5',
    ),

    // Subcategories for Groceries & Food
    CategoryModel(
      id: 601,
      name: 'Fresh Produce',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),
    CategoryModel(
      id: 602,
      name: 'Dairy & Eggs',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),
    CategoryModel(
      id: 603,
      name: 'Meat & Seafood',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),
    CategoryModel(
      id: 604,
      name: 'Snacks & Confectionery',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),
    CategoryModel(
      id: 605,
      name: 'Pantry Staples',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),
    CategoryModel(
      id: 606,
      name: 'Beverages',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),
    CategoryModel(
      id: 607,
      name: 'Frozen Foods',
      image: '',
      isFeatured: false,
      parentId: '6',
    ),

    // Subcategories for Baby & Kids Products
    CategoryModel(
      id: 701,
      name: 'Baby Clothing',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 702,
      name: 'Diapers & Wipes',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 703,
      name: 'Baby Gear & Accessories',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 704,
      name: 'Baby Feeding',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 705,
      name: 'Toys & Games',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 706,
      name: 'Kids’ Clothing',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 707,
      name: 'Kids’ Shoes',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 708,
      name: 'Baby Health & Safety',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 709,
      name: 'Baby Bath & Skincare',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),
    CategoryModel(
      id: 710,
      name: 'Nursery & Decor',
      image: '',
      isFeatured: false,
      parentId: '7',
    ),

    // Subcategories for Home & Furniture
    CategoryModel(
      id: 801,
      name: 'Living Room Furniture',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 802,
      name: 'Bedroom Furniture',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 803,
      name: 'Kitchen & Dining Furniture',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 804,
      name: 'Office Furniture',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 805,
      name: 'Storage & Organization',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 806,
      name: 'Home Decor',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 807,
      name: 'Lighting & Fixtures',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 808,
      name: 'Bedding & Linens',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 809,
      name: 'Outdoor & Patio Furniture',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),
    CategoryModel(
      id: 810,
      name: 'Home Improvement & Repair',
      image: '',
      isFeatured: false,
      parentId: '8',
    ),

    // Subcategories for Office & School Supplies
    CategoryModel(
      id: 901,
      name: 'Writing & Drawing Instruments',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 902,
      name: 'Notebooks & Paper Products',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 903,
      name: 'Office Equipment',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 904,
      name: 'School Essentials',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 905,
      name: 'Filing & Organization',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 906,
      name: 'Presentation & Display Supplies',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 907,
      name: 'Office Furniture & Accessories',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 908,
      name: 'Art & Craft Supplies',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 909,
      name: 'Printers & Scanners',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),
    CategoryModel(
      id: 910,
      name: 'Educational Materials',
      image: '',
      isFeatured: false,
      parentId: '9',
    ),

    // Subcategories for Sports & Outdoors
    CategoryModel(
      id: 1001,
      name: 'Fitness & Exercise Equipment',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1002,
      name: 'Outdoor Recreation',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1003,
      name: 'Team Sports',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1004,
      name: 'Individual Sports',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1005,
      name: 'Cycling',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1006,
      name: 'Water Sports',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1007,
      name: 'Winter Sports',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1008,
      name: 'Camping & Hiking',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1009,
      name: 'Fishing & Hunting',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),
    CategoryModel(
      id: 1010,
      name: 'Skating & Skateboarding',
      image: '',
      isFeatured: false,
      parentId: '10',
    ),

    // Subcategories for Automotive & Motorcycles
    CategoryModel(
      id: 1101,
      name: 'Car Accessories',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1102,
      name: 'Motorcycle Accessories',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1103,
      name: 'Car Parts & Components',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1104,
      name: 'Motorcycle Parts & Components',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1105,
      name: 'Car Electronics',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1106,
      name: 'Motorcycle Gear & Apparel',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1107,
      name: 'Car Maintenance & Cleaning',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1108,
      name: 'Motorcycle Maintenance & Cleaning',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1109,
      name: 'Tires & Wheels',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),
    CategoryModel(
      id: 1110,
      name: 'Oil & Fluids',
      image: '',
      isFeatured: false,
      parentId: '11',
    ),

    // Subcategories for Pet Supplies
    CategoryModel(
      id: 1201,
      name: 'Pet Food',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1202,
      name: 'Pet Toys',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1203,
      name: 'Pet Grooming & Hygiene',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1204,
      name: 'Pet Beds & Furniture',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1205,
      name: 'Pet Clothing & Accessories',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1206,
      name: 'Pet Health & Wellness',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1207,
      name: 'Pet Training & Behavior',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1208,
      name: 'Pet Travel & Carriers',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1209,
      name: 'Aquariums & Fish Supplies',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),
    CategoryModel(
      id: 1210,
      name: 'Bird Supplies',
      image: '',
      isFeatured: false,
      parentId: '12',
    ),

    // Subcategories for Books & Stationery
    CategoryModel(
      id: 1301,
      name: 'Fiction Books',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1302,
      name: 'Non-Fiction Books',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1303,
      name: 'Academic & Educational Books',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1304,
      name: 'Children’s Books',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1305,
      name: 'Comics & Graphic Novels',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1306,
      name: 'Stationery & Office Supplies',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1307,
      name: 'Art & Craft Supplies',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1308,
      name: 'Diaries & Planners',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1309,
      name: 'Writing Instruments',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1310,
      name: 'Notebooks & Journals',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),
    CategoryModel(
      id: 1311,
      name: 'Bookmarks & Reading Accessories',
      image: '',
      isFeatured: false,
      parentId: '13',
    ),

    // Subcategories for Jewelry & Accessories
    CategoryModel(
      id: 1401,
      name: 'Necklaces & Pendants',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1402,
      name: 'Earrings',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1403,
      name: 'Bracelets & Bangles',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1404,
      name: 'Rings',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1405,
      name: 'Anklets',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1406,
      name: 'Watches',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1407,
      name: 'Brooches & Pins',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1408,
      name: 'Hair Accessories',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1409,
      name: 'Sunglasses & Eyewear',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),
    CategoryModel(
      id: 1410,
      name: 'Jewelry Storage & Organizers',
      image: '',
      isFeatured: false,
      parentId: '14',
    ),

    // Subcategories for Home Improvement & Tools
    CategoryModel(
      id: 1501,
      name: 'Hand Tools',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1502,
      name: 'Power Tools',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1503,
      name: 'Hardware & Fasteners',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1504,
      name: 'Plumbing Supplies',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1505,
      name: 'Electrical Supplies',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1506,
      name: 'Lighting & Fixtures',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1507,
      name: 'Paint & Wall Treatments',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1508,
      name: 'Ladders & Workbenches',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1509,
      name: 'Locks & Security Systems',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
    CategoryModel(
      id: 1510,
      name: 'Building Materials',
      image: '',
      isFeatured: false,
      parentId: '15',
    ),
  ];
}
